eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0

    propagation:
      type: b3

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans



okta:
  oauth2:
    issuer: https://dev-2k04qtmjjraf63du.us.auth0.com/
    audience: api://default

